M48
; DRILL file {KiCad 7.0.11+dfsg-1build4} date Fri Oct  2 04:18:51 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-10-02T04:18:51+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.11+dfsg-1build4
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X3.5Y-3.5
X3.5Y-78.5
X96.5Y-3.5
X96.5Y-78.5
M30
